# Generated by Django 3.0.1 on 2019-12-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20191223_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
