# Generated by Django 3.0.1 on 2019-12-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_routine_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='taskresult',
            name='parent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
