# Generated by Django 3.0.1 on 2019-12-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20191230_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='spawn',
            field=models.ManyToManyField(blank=True, to='machine.TaskConnection'),
        ),
        migrations.AddField(
            model_name='taskconnection',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
