# Generated by Django 3.0.1 on 2020-01-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_auto_20200101_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskerror',
            name='task_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
